### ISSUE TITLE
support for dynamic targets

### ISSUE THREAD

**Issue by jensenja** [houqp/iris-python-client#3]
Hi,

iris-python-client doesn't seem to support POST'ing to [incidents with dynamic targets](https://iris.claims/docs/rest_api.html#v0-incidents) as it currently stands.

I was able to make the following hack in `__init__.py`:

    def incident(self, plan, context, dynamic=None):
        if dynamic:
            r = self.post(self.url + 'incidents',
                json={'plan': plan, 'context': context, 'dynamic_targets': dynamic})

And then in my test script:

    #!/usr/bin/env python

    from irisclient import IrisClient

    client = IrisClient(app='oncall', key='my_key', api_host='http://iris.example.com')
    client.incident('oncall_standard', context={'requester': 'me', 'description': 'something went wrong'}, dynamic=[{'role': 'team', 'target':'Network Operations'}])

The call fails:

    root@79a7f689536f:~# ./test.py
    Traceback (most recent call last):
      File "./test.py", line 6, in <module>
        client.incident('oncall_standard', context={'requester': 'me', 'description': 'something went wrong'}, dynamic=[{'role': 'team', 'target':'Network Operations'}])
      File "/usr/local/lib/python2.7/dist-packages/irisclient/__init__.py", line 60, in incident
        r.raise_for_status()
      File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 939, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://iris.example.com/v0/incidents

But the incidents are still created and I can see them in Iris, as well as receive notifications about them, so it seems as though the API returns a 400 but still processes them normally?

**Comment by jensenja** [comment]
Also for what it's worth I'm not using SSL in my Iris deployment (you guys really seem to like enforcing SSL without giving a choice to the consumer of your APIs ;-) ) and I have changed `session_opts` in `iris/src/iris/ui/__init.py__` to the following (to get around the login page loop bug mentioned [here](https://github.com/linkedin/iris/issues/281#issuecomment-346592698)):

        session_opts = {
            'session.type': 'cookie',
            'session.cookie_expires': True,
            'session.key': 'iris-auth',
            'session.encrypt_key': config['user_session']['encrypt_key'],
            'session.validate_key': config['user_session']['sign_key'],
            #'session.secure': not (config['server'].get('disable_auth', False) or config['server'].get('allow_http', False)),
            'session.secure': False,
            'session.httponly': True
        }

Why `session.secure` isn't respecting `allow_http: True` in `config.yaml` is a mystery to me.

**Comment by jensenja** [comment]
it looks like @dwang159 added support for dynamic targets in his fork. I will test with his.

**Comment by jensenja** [comment]
his fork works and does not result in a 400 returned. closing.
